### ISSUE TITLE
My ReadyNAS 212 does not cooperate with Logitech Media Server?

### ISSUE THREAD

**Issue by jpheyer** [NAStools/logitechmediaserver#1]
I just got a Netgear ReadyNAS 212 up and running to replace my old ReadyNAS DUO where my Squeezebox Radio was linked.

The application "nastools-logitechmediaserver_7.9.0.b7dfc80-nt1_armel.deb"  claims to be installed successfully.

It does, however, NOT launch as expected.  The ON button keeps dead and "a toggling service" starts and ends. 

Could anybody out there help? 

Much appreciated!

JP

**Comment by petros265** [comment]
The issue looks the same I have.  The underlying error which causes it to crash is Empty Resource Error.  Bad NML call.  I am also looking for a solution.  Peter

**Comment by petros265** [comment]
I removed the Nastools version and installed this version from github.

https://github.com/NAStools/logitechmediaserver/releases/download/readynas%2F7.9.0_1477086729-nt1/nastools-logitechmediaserver_7.9.0.1477086729-nt1_armel.deb

It is slightly smaller.  Initially it gave the same error message but after 5 minutes or so it spontaneously started.  I now have full functionality with my Logitech Squeezeboxes with an updated Controller with different menu structure.

I hope that helps.

Peter

**Comment by jpheyer** [comment]
Peter!

 

You made my day!

 

The GitHub download suggested, works well, and my old Squeezebox Radio gets some more years in service, running on my new ReadyNAS 212.

 

Thanks for sharing your wisdom.

 

JP

 

Fra: petros265 [mailto:notifications@github.com] 
Sendt: tirsdag 13. desember 2016 20.14
Til: NAStools/logitechmediaserver
Kopi: jpheyer; Author
Emne: Re: [NAStools/logitechmediaserver] My ReadyNAS 212 does not cooperate with Logitech Media Server? (#1)

 

I removed the Nastools version and installed this version from github.

https://github.com/NAStools/logitechmediaserver/releases/download/readynas%2F7.9.0_1477086729-nt1/nastools-logitechmediaserver_7.9.0.1477086729-nt1_armel.deb

It is slightly smaller. Initially it gave the same error message but after 5 minutes or so it spontaneously started. I now have full functionality with my Logitech Squeezeboxes with an updated Controller with different menu structure.

I hope that helps.

Peter
